#!/bin/bash

NAME="vine"                                                       # Name of the application
DJANGODIR=/git/vine/server/d1                                     # Django project directory
HOME=/root
VEDIR=$HOME/vine/                                                     # Virtual Env directory
SOCKFILE=$VEDIR/run/gunicorn.sock                                 # we will communicte using this unix socket
USER=root                                                         # the user to run as
GROUP=root                                                        # the group to run as
NUM_WORKERS=3                                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=d1.settings                                # which settings file should Django use
DJANGO_WSGI_MODULE=d1.wsgi                                        # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $VEDIR/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $HOME/vine/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug --debug \
  --bind=unix:$SOCKFILE
